#!/usr/bin/env python3

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
MANIFEST = SKILLS / "manifest.txt"
NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
FRONTMATTER = re.compile(r"\A---\n(?P<header>.*?)\n---(?P<body>\n.*)\Z", re.DOTALL)
REFERENCE = re.compile(r"`((?:\.\./|references/)[^`]+\.md)`")
ALLOWED_FIELDS = {"name", "description", "user-invocable", "argument-hint"}
RETIRED = {
    "apple-ship",
    "aws-ship",
    "azure-ship",
    "cloudflare-ship",
    "google-cloud-ship",
    "supabase-ship",
    "vercel-ship",
}
TEXT_SURFACES = (
    REPO / "README.md",
    REPO / "INSTALL.md",
    REPO / "guide",
    REPO / "recipes",
    REPO / "templates",
    REPO / ".github" / "agents",
    REPO / "codex",
    REPO / "claude" / "agents",
    REPO / "openclaw" / "skills",
    SKILLS,
)


def text_files(surface: Path) -> list[Path]:
    if surface.is_file():
        return [surface]
    return sorted(path for path in surface.rglob("*.md") if path.is_file())


def parse_header(path: Path) -> dict[str, str]:
    match = FRONTMATTER.match(path.read_text(encoding="utf-8"))
    if not match:
        raise ValueError("missing canonical YAML frontmatter")
    fields: dict[str, str] = {}
    for line in match.group("header").splitlines():
        key, separator, value = line.partition(":")
        if not separator or not key or key != key.strip():
            raise ValueError(f"unsupported frontmatter line {line!r}")
        if key in fields:
            raise ValueError(f"duplicate frontmatter field {key!r}")
        fields[key] = value.strip().strip("\"'")
    return fields


def main() -> int:
    problems: list[str] = []
    entries = [line.strip() for line in MANIFEST.read_text(encoding="utf-8").splitlines() if line.strip()]
    if len(entries) != len(set(entries)):
        problems.append(f"{MANIFEST}: duplicate entries")

    published = {entry for entry in entries if entry != "_house-style"}
    discovered = {path.parent.name for path in SKILLS.glob("*/SKILL.md")}
    if published != discovered:
        problems.append(
            f"{MANIFEST}: missing={sorted(published - discovered)}; unpublished={sorted(discovered - published)}"
        )

    variants = sorted(
        {
            path
            for path in SKILLS.rglob("*.md")
            if (path.name.startswith("SKILL") and path.name != "SKILL.md")
            or re.search(r" \d+\.md$", path.name)
        }
    )
    problems.extend(f"{path}: stale or duplicate skill entrypoint" for path in variants)

    source_ui_metadata = sorted(SKILLS.glob("*/agents/openai.yaml"))
    problems.extend(
        f"{path}: Codex UI metadata is generated by sync-codex-skills.py and must not live in source"
        for path in source_ui_metadata
    )

    total_lines = 0
    for skill in sorted(published):
        if not NAME.fullmatch(skill) or len(skill) > 64:
            problems.append(f"{skill}: invalid skill name")
            continue
        path = SKILLS / skill / "SKILL.md"
        try:
            fields = parse_header(path)
        except (OSError, ValueError) as error:
            problems.append(f"{path}: {error}")
            continue
        unexpected = set(fields) - ALLOWED_FIELDS
        if unexpected:
            problems.append(f"{path}: unsupported fields {sorted(unexpected)}")
        if fields.get("name") != skill:
            problems.append(f"{path}: frontmatter name must equal directory name")
        description = fields.get("description", "")
        if not description or not any(trigger in description for trigger in ("Use when", "Use immediately", "Use after", "Use for")):
            problems.append(f"{path}: description must state when to use the skill")
        if len(description) > 1024 or "<" in description or ">" in description:
            problems.append(f"{path}: description violates Codex constraints")
        source = path.read_text(encoding="utf-8")
        lines = len(source.splitlines())
        total_lines += lines
        if lines > 300:
            problems.append(f"{path}: {lines} lines exceeds the 300-line bench budget")
        for relative in REFERENCE.findall(source):
            if not (path.parent / relative).resolve().is_file():
                problems.append(f"{path}: missing referenced file {relative}")

    retired_names = "|".join(sorted(RETIRED, key=len, reverse=True))
    retired_pattern = re.compile(
        r"(?:(?<![A-Za-z0-9_.-])[/\$](?P<command>" + retired_names + r")\b"
        r"|skills:\s*\[[^\]]*\b(?P<binding>" + retired_names + r")\b)"
    )
    for surface in TEXT_SURFACES:
        for path in text_files(surface):
            if path == REPO / "CHANGELOG.md":
                continue
            for match in retired_pattern.finditer(path.read_text(encoding="utf-8")):
                retired = match.group("command") or match.group("binding")
                problems.append(f"{path}: retired skill invocation {retired!r}")

    trigger_path = REPO / "eval" / "trigger-cases.json"
    try:
        trigger_cases = json.loads(trigger_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        problems.append(f"{trigger_path}: {error}")
        trigger_cases = {}
    if set(trigger_cases) != published:
        problems.append(
            f"{trigger_path}: missing={sorted(published - set(trigger_cases))}; stale={sorted(set(trigger_cases) - published)}"
        )
    for skill, cases in trigger_cases.items():
        if not isinstance(cases, dict):
            problems.append(f"{trigger_path}: {skill} must map to an object")
            continue
        for polarity in ("positive", "negative"):
            prompts = cases.get(polarity)
            if not isinstance(prompts, list) or not prompts or not all(isinstance(prompt, str) and prompt.strip() for prompt in prompts):
                problems.append(f"{trigger_path}: {skill}.{polarity} requires at least one non-empty prompt")

    if problems:
        print("\n".join(f"ERROR: {problem}" for problem in problems), file=sys.stderr)
        return 1

    print(f"Skill bench validation passed for {len(published)} skills ({total_lines} SKILL.md lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
